### ISSUE TITLE
쉘 스크립트 대응

### ISSUE THREAD

**Issue by zlzleking** [LiteHell/NamuForker4MW#2]
현재의 방식으로는 다량의 문서를 가져올 때 수작업으로 해야 해서 불편합니다.

따라서 명령어를

node index.js -문서 이름 -저장할 경로

식으로 할 수 있게 한다면 상당히 유용할 것 같습니다.

**Comment by LiteHell** [comment]
커밋 12b82a26b811b018ee51a3fcbc7230a13c41a5bd 에서 --svaeTo와 --articleName 매개변수로 지정하도록 수정했고, >=3.0.0에서 사용 가능합니다.
